# Database
database:
  url: localhost
  port: 27017
  username: admin
  password: password
  database: bolster

# Active gamemode
gamemode: bolster

# Common text
game-name: Bolster
short-game-name: Bolster
long-game-name: Bolster
ip-address: runed.co
website-url: runed.co
store-url: runed.co

# Premium
premium-member-name: Super Jimmy

# Available slots for premium members
premium-slots: 10

# Cleanup
cleanup-players: true
cleanup-frequency: 12000 # 10 minutes
force-cleanup-time: 72000 # The amount of time a player has to be disconnected for to be force cleaned up (default 1 hour)

# Saving
auto-save: true
auto-save-frequency: 1200 # Auto-save player data every x ticks (default 1 minute)